### ISSUE TITLE
Give error when try to open local Payment Method in Kuwait

### ISSUE THREAD

**Issue by movaliyaprashant** [Mixpeal/flutter_tap_payment#3]
if i am try with  "source": {"id": "src_kw.knet"}  this for open local payment method in Kuwait then give me this error {errors: [{code: 1172, description: Destination id is invalid}], http_code: 400}.

Documantation : https://developers.dev.tap.company/reference/charges-2

**Comment by Mixpeal** [comment]
Hello, are you still having this issue?
